INSERT INTO plan_addons (
  code,
  name,
  description,
  monthly_price_cents,
  provider_cost_cents,
  is_active,
  sort_order,
  available_plan_codes,
  included_plan_codes,
  settings,
  created_at,
  updated_at
) VALUES
  (
    'payment_setup_assisted',
    'Configuração Assistida do Pix Online',
    'A equipe TáPronto orienta a ativação da Abacate Pay, confere webhook e valida um pagamento de teste.',
    7990,
    0,
    true,
    50,
    ARRAY['essential','professional'],
    ARRAY['premium'],
    '{"billing_type":"one_time","service_type":"assisted_setup","support_category":"Pagamento online","support_subject":"Configurar pagamento online com Abacate Pay"}'::jsonb,
    now(),
    now()
  ),
  (
    'whatsapp_setup_assisted',
    'Configuração Assistida do WhatsApp Automático',
    'A equipe TáPronto ajuda a conectar o WhatsApp por QR Code e testar o envio automático de pedidos.',
    9990,
    0,
    true,
    60,
    ARRAY['professional','premium'],
    ARRAY[]::text[],
    '{"billing_type":"one_time","service_type":"assisted_setup","support_category":"WhatsApp","support_subject":"Configurar WhatsApp automático"}'::jsonb,
    now(),
    now()
  ),
  (
    'store_setup_assisted',
    'Configuração Inicial da Loja',
    'A equipe TáPronto ajuda a revisar loja, horários, entrega, formas de pagamento e publicação.',
    14990,
    0,
    true,
    70,
    ARRAY['essential','professional','premium'],
    ARRAY[]::text[],
    '{"billing_type":"one_time","service_type":"assisted_setup","support_category":"Configuração da loja","support_subject":"Configuração inicial assistida da loja"}'::jsonb,
    now(),
    now()
  ),
  (
    'menu_import_assisted',
    'Cadastro Assistido do Cardápio',
    'A equipe TáPronto cadastra categorias, produtos, preços, fotos e adicionais iniciais enviados pela loja.',
    19990,
    0,
    true,
    80,
    ARRAY['essential','professional','premium'],
    ARRAY[]::text[],
    '{"billing_type":"one_time","service_type":"assisted_setup","support_category":"Cardápio e produtos","support_subject":"Cadastro assistido do cardápio"}'::jsonb,
    now(),
    now()
  ),
  (
    'training_assisted',
    'Treinamento Rápido da Equipe',
    'Uma sessão guiada para explicar pedidos, cardápio, operação, suporte e boas práticas do TáPronto.',
    7990,
    0,
    true,
    90,
    ARRAY['essential','professional','premium'],
    ARRAY[]::text[],
    '{"billing_type":"one_time","service_type":"assisted_setup","support_category":"Treinamento","support_subject":"Treinamento rápido da equipe"}'::jsonb,
    now(),
    now()
  ),
  (
    'full_implementation_package',
    'Implantação Completa TáPronto',
    'Pacote completo com configuração da loja, cardápio inicial, Pix online, WhatsApp automático e treinamento.',
    39990,
    0,
    true,
    100,
    ARRAY['professional','premium'],
    ARRAY[]::text[],
    '{"billing_type":"one_time","service_type":"assisted_setup","support_category":"Implantação","support_subject":"Implantação completa assistida"}'::jsonb,
    now(),
    now()
  )
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  monthly_price_cents = EXCLUDED.monthly_price_cents,
  provider_cost_cents = EXCLUDED.provider_cost_cents,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  available_plan_codes = EXCLUDED.available_plan_codes,
  included_plan_codes = EXCLUDED.included_plan_codes,
  settings = EXCLUDED.settings,
  updated_at = now();
