server {
    listen 80;
    listen [::]:80;
    server_name guias.taprontomenu.com.br;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name guias.taprontomenu.com.br;

    ssl_certificate /etc/letsencrypt/live/taprontomenu.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/taprontomenu.com.br/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:TaprontoGuidesSSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location = / {
        return 301 https://taprontomenu.com.br/guias;
    }

    location = /guias {
        return 301 https://taprontomenu.com.br/guias;
    }

    location ^~ /guias/ {
        return 301 https://taprontomenu.com.br$request_uri;
    }

    location / {
        return 301 https://taprontomenu.com.br/guias$request_uri;
    }
}
